@StanNaDanWebAPIService_HostAddress = http://localhost:5268

GET {{StanNaDanWebAPIService_HostAddress}}/weatherforecast/
Accept: application/json

###

###-----------------------------------POSLOVNICE---------------------------------------------


GET {{StanNaDanWebAPIService_HostAddress}}/Poslovnica/VratiSvePoslovnice
Accept: application/json
### Vracanje svih poslovnica


GET {{StanNaDanWebAPIService_HostAddress}}/Poslovnica/VratiPoslovnicu/1
Accept: application/json
### Vraca poslovnicu na osnovu ID


POST {{StanNaDanWebAPIService_HostAddress}}/Poslovnica/DodajPoslovnicu
Content-Type: application/json

{
  "adresa" : "PIROT, Slavonska 98",
  "radnoVreme" : "13:00 - 05:00h"
}
### Testira dodavanje nove poslovnice


PUT {{StanNaDanWebAPIService_HostAddress}}/Poslovnica/IzmeniPoslovnicu/61
Content-Type: application/json

{
  "adresa" : "NIS, Milojka Lesnjanina 18",
  "radnoVreme" : "12:00 - 04:00h"
}
### Menja adresu i radno vreme poslovnice sa ID 1


###-----------------------------------KVART--------------------------------------------------



GET {{StanNaDanWebAPIService_HostAddress}}/Kvart/VratiSveKvartove
Accept: application/json
### Vracanje svih kvartova


GET {{StanNaDanWebAPIService_HostAddress}}/Kvart/VratiSveKvartovePoslovnice/1
Accept: application/json
### Vraca sve kvartove poslovnice na osnovu ID


GET {{StanNaDanWebAPIService_HostAddress}}/Kvart/VratiKvart/1
Accept: application/json
### Vraca kvart na osnovu ID


POST {{StanNaDanWebAPIService_HostAddress}}/Kvart/DodajNoviKvart/1
Content-Type: application/json

{
  "gradskaZona" : "Tijabara"
}
### Dodaje novi kvart poslovnici sa ID 1


PUT {{StanNaDanWebAPIService_HostAddress}}/Kvart/IzmeniKvart/42
Content-Type: application/json

{
    "gradskaZona" : "Medijana"
}
### Menja gradsku zonu kvarta sa ID 1


DELETE {{StanNaDanWebAPIService_HostAddress}}/Kvart/ObrisiKvart/42
### Brisemo kvart sa ID 22


//DELETE {{StanNaDanWebAPIService_HostAddress}}/Vlasnik/ObrisiVlasnika?pib=987654321
### Brisemo vlasnika sa ID 



###-----------------------------------PRAVNO_LICE----------------------------------------------------------

GET {{StanNaDanWebAPIService_HostAddress}}/PravnoLice/VratiSvaPravnaLica
Accept: application/json
### Vraca sva pravna lica


GET {{StanNaDanWebAPIService_HostAddress}}/PravnoLice/VratiPravnoLice/123456789
Accept: application/json
### Vraca pravno lice na osnovu ID


POST {{StanNaDanWebAPIService_HostAddress}}/PravnoLice/DodajNovoPravnoLice
Content-Type: application/json

{
  "pib": "129496989",
  "naziv": "DELI",
  "adresaSedista": "PIROT, Kapetana Karanovica 44",
  "imeKontaktOsobe": "Predrag Ostojic",
  "emailKontaktOsobe": "ostoje@gmail.com",
  "vlasnik": {
    "banka": "Erste Bank",
    "brojBankovnogRacuna": "987994144"
  }
}
### Dodaje novi kvart poslovnici sa ID 1


PUT {{StanNaDanWebAPIService_HostAddress}}/PravnoLice/IzmeniPravnoLice/129496989
Content-Type: application/json

{
  "pib": "129496989",
  "naziv": "DELI",
  "adresaSedista": "PIROT, Kapetana Karanovica 44",
  "imeKontaktOsobe": "Nebojsa Ostojic",
  "emailKontaktOsobe": "ostoje@gmail.com",
  "vlasnik": {
    "banka": "Erste Bank",
    "brojBankovnogRacuna": "987994154"
  }
}
### Menja ime kontakt osobe i broj bankovnog racuna pravnog lica sa ID 


DELETE {{StanNaDanWebAPIService_HostAddress}}/PravnoLice/ObrisiPravnoLice/129496989
### Brisemo kvart sa ID 129496989


###-----------------------------------FIZICKO_LICE----------------------------------------


GET {{StanNaDanWebAPIService_HostAddress}}/FizickoLice/VratiSvaFizickaLica
Accept: application/json
### Vraca sva fizicka lica


POST {{StanNaDanWebAPIService_HostAddress}}/FizickoLice/DodajNovoFizickoLice
Content-Type: application/json

{
  "jmbg": "1234567890444",
  "ime": "Kosta",
  "imeRoditelja": "Milan",
  "prezime": "Arsic",
  "drzava": "Srbija",
  "mestoStanovanja": "Beograd",
  "adresaStanovanja": "Brace Jerkovica 45",
  "datumRodjenja": "2000-11-07T00:00:00",
  "email": "arsa@elfak.rs",
  "vlasnik": {
    "banka": "Raiffeisen Banka Srbije",
    "brojBankovnogRacuna": "123456780"
  }
}
### Dodaje novo fizicko lice



GET {{StanNaDanWebAPIService_HostAddress}}/FizickoLice/VratiFizickoLice/1234567890444
Accept: application/json
### Vraca fizicko lice na osnovu JMBG


PUT {{StanNaDanWebAPIService_HostAddress}}/FizickoLice/IzmeniFizickoLice/1234567890444
Content-Type: application/json

{
  "jmbg": "1234567890444",
  "ime": "Ostoje",
  "imeRoditelja": "Milan",
  "prezime": "Arsic",
  "drzava": "Srbija",
  "mestoStanovanja": "Beograd",
  "adresaStanovanja": "Brace Jerkovica 45",
  "datumRodjenja": "2000-11-07T00:00:00",
  "email": "ostoje@elfak.rs",
  "vlasnik": {
    "banka": "Raiffeisen Banka Srbije",
    "brojBankovnogRacuna": "123006780"
  }
}
### Menja ime, email i broj bankovnog racuna fizicko lice


DELETE {{StanNaDanWebAPIService_HostAddress}}/FizickoLice/ObrisiFizickoLice/1234567890444
### Brisemo fizicko lice sa JMBG 1234567890444



DELETE {{StanNaDanWebAPIService_HostAddress}}/Poslovnica/ObrisiPoslovnicu/45
### Testiranje brisanja poslovnice sa id 45, na adresi slavonska 88


###-----------------------------------ZAPOSLENI---------------------------------------------
  
GET {{StanNaDanWebAPIService_HostAddress}}/Zaposleni/VratiSveZaposlene
Accept: application/json
### Testira vracanje i prikaz svih zaposlenih u bazi


GET {{StanNaDanWebAPIService_HostAddress}}/Zaposleni/VratiSveZaposlenePoslovnice/1
Accept:application/json
### Testira vracanje zaposlenih iz poslovnice ciji id je prosledjen


GET {{StanNaDanWebAPIService_HostAddress}}/Zaposleni/VratiZaposlenog/4444444444444
Accept:application/json
### Testira vracanje zaposlenog na osnovu maticnog broja


DELETE {{StanNaDanWebAPIService_HostAddress}}/Zaposleni/ObrisiZaposlenog/1107002732599
### Testira brisanje zaposlenog sa zadatim ID (taj koji se brise zove se Obrisi Obrisi)
### (Napomena) Dodavanje zaposlenih se vrsi kroz funkcije dodajAgenta i dodajSefa kroz respektivne kontrolere


###-----------------------------------AGENTI---------------------------------------------

GET {{StanNaDanWebAPIService_HostAddress}}/Agent/VratiSveAgente
Accept:application/json
### Testira vracanje svih agenta iz baze podataka


GET {{StanNaDanWebAPIService_HostAddress}}/Agent/VratiSveAgentePoslovnice/1
Accept:application/json
### Testira vracanje svih agenta iz baze podataka


GET {{StanNaDanWebAPIService_HostAddress}}/Agent/VratiAgenta/1107002732566
Accept:application/json
### Testira vracanje agenta na osnovu maticnog broja


POST {{StanNaDanWebAPIService_HostAddress}}/Agent/DodajAgenta/41
Content-Type:application/json

{
  "mbr": "1107002732577",
  "ime": "Milorad",
  "prezime": "Dodati",
  "datumZaposlenja": "2024-06-16T01:15:14.547Z",
  "strucnaSprema": "Diplomirani ekonomista"
}
### Testira dodavanje novog agenta i njegovo zaposljavanje u poslovnicu sa ID 41


PUT {{StanNaDanWebAPIService_HostAddress}}/Agent/IzmeniAgenta/1107002732577
Content-Type:application/json

{
  "ime": "Milorad",
  "prezime": "Izmenjeni",
  "datumZaposlenja": "2024-06-16T01:15:14.547Z",
  "strucnaSprema": "Master ekonomista"
}
### Testira izmenu agenta na osnovu maticnog broja
### (Napomena) brisanje agenta, kao i brisanje sefa, vrsi se kroz prethodno demonstriranu funkciju ObrisiZaposlenog


###-----------------------------------SPOLJNI SARADNICI---------------------------------------------

GET {{StanNaDanWebAPIService_HostAddress}}/SpoljniSaradnik/VratiSveSpoljneSaradnike
Accept:application/json
### Testira vracanje svih spoljnih saradnika iz baze podataka


GET {{StanNaDanWebAPIService_HostAddress}}/SpoljniSaradnik/VratiSveSpoljneSaradnikeAgenta/4444444444444
Accept:application/json
### Testira vracanje svih spoljnih saradnika agenta sa prosledjenim maticnim brojem


GET {{StanNaDanWebAPIService_HostAddress}}/SpoljniSaradnik/VratiSpoljnogSaradnika/4444444444444/1
Accept:application/json
### Testira vracanje spoljnog saradnika na osnovu njegovog id u okviru agenta sa prosledjenim maticnim brojem


POST {{StanNaDanWebAPIService_HostAddress}}/SpoljniSaradnik/DodajSpoljnogSaradnika/4444444444444/2
Content-Type:application/json

{
  "ime": "Vukoje",
  "prezime": "Vukojevic",
  "datumAngazovanja": "2024-06-17T11:46:43.314Z",
  "telefon": "063 492989",
  "procenatOdNajma": 10
}
### Testira dodavanje novog spoljnog saradnika agentu sa prosledjenim maticnim brojem


PUT {{StanNaDanWebAPIService_HostAddress}}/SpoljniSaradnik/IzmeniSpoljnogSaradnika/4444444444444/2
Content-Type:application/json

{
  "ime": "Vukoje",
  "prezime": "Vukojevichius",
  "datumAngazovanja": "2024-06-17T11:46:43.314Z",
  "telefon": "063 492989",
  "procenatOdNajma": 15
}
### Testira menjanje spoljnog saradnika (prethodno dodatog)


DELETE {{StanNaDanWebAPIService_HostAddress}}/SpoljniSaradnik/ObrisiSpoljnogSaradnika/4444444444444/2
### Testira brisanje prethodno kreiranog spoljnog saradnika



###-----------------------------------SEFOVI---------------------------------------------

GET {{StanNaDanWebAPIService_HostAddress}}/Sef/VratiSveSefove
Accept:application/json
### Testira vracanje svih sefova iz baze podataka


GET {{StanNaDanWebAPIService_HostAddress}}/Sef/VratiSefa/1111111111111
Accept:application/json
### Testira vracanje sefa na osnovu maticnog broja


GET {{StanNaDanWebAPIService_HostAddress}}/Sef/VratiSefaPoslovnice/1
Accept:application/json
### Testira vracanje sefa prosledjene poslovnice


POST {{StanNaDanWebAPIService_HostAddress}}/Sef/DodajNovogSefa/41
Content-Type:application/json

{
  "mbr": "1107002732523",
  "ime": "Milorad",
  "prezime": "DodatiSef",
  "datumZaposlenja": "2024-06-16T01:15:14.547Z",
  "datumPostavljanja": "2024-06-16T01:15:14.547Z"
}
### Testira dodavanje novog sefa i njegovo postavljanje u poslovnicu sa ID 41


PUT {{StanNaDanWebAPIService_HostAddress}}/Sef/IzmeniSefa/1107002732523
Content-Type:application/json

{
  "ime": "Milorad",
  "prezime": "IzmenjeniSef",
  "datumZaposlenja": "2024-06-16T01:15:14.547Z",
  "datumPostavljanja": "2024-06-16T01:15:14.547Z"
}
### Testira izmenu podataka o sefu


  
###-----------------------------------NEKRETNINE---------------------------------------------

  
GET {{StanNaDanWebAPIService_HostAddress}}/Nekretnina/VratiSveNekretnine
Accept:application/json
### Testira vracanje svih nekretnina iz baze


GET {{StanNaDanWebAPIService_HostAddress}}/Nekretnina/VratiNekretninu/1
Accept:application/json
### Testira vracanje nekretnine na osnovu prosledjenog ID

  
GET {{StanNaDanWebAPIService_HostAddress}}/Nekretnina/VratiSveNekretnineKvarta/1
Accept:application/json
### Testira vracanje svih nekretnina na prosledjenom kvartu


GET {{StanNaDanWebAPIService_HostAddress}}/Nekretnina/VratiSveNekretnineVlasnika/1
Accept:application/json
### Testira vracanje svih nekretnina u posedu vlasnika sa prosledjenim ID


POST {{StanNaDanWebAPIService_HostAddress}}/Nekretnina/DodajKucu/1/1
Content-Type:application/json

{
  "ulica": "PIROT, Probna ulica",
  "broj": "66",
  "kvadratura": 200,
  "brojTerasa": 4,
  "brojKupatila": 2,
  "brojSpavacihSoba": 4,
  "posedujeTV": true,
  "posedujeInternet": true,
  "posedujeKuhinju": true,
  "spratnost": 2,
  "posedujeDvoriste": true
}
### Testira dodavanje nove kuce vlasniku sa prosledjenim ID, na kvartu sa prosledjenim ID (prvo ide idKvarta)


POST {{StanNaDanWebAPIService_HostAddress}}/Nekretnina/DodajStan/1/1
Content-Type:application/json

{
  "ulica": "Probna Ulica",
  "broj": "77",
  "kvadratura": 50,
  "brojTerasa": 1,
  "brojKupatila": 1,
  "brojSpavacihSoba": 1,
  "posedujeTV": true,
  "posedujeInternet": true,
  "posedujeKuhinju": true,
  "sprat": 2,
  "posedujeLift": true
}
### Testira dodavanje novog stana postojecem vlasniku na postojecem kvartu


PUT {{StanNaDanWebAPIService_HostAddress}}/Nekretnina/IzmeniKucu/41
Content-Type:application/json

{
  "ulica": "PIROT, Probna ulica izmenjena",
  "broj": "66",
  "kvadratura": 200,
  "brojTerasa": 4,
  "brojKupatila": 2,
  "brojSpavacihSoba": 4,
  "posedujeTV": true,
  "posedujeInternet": true,
  "posedujeKuhinju": true,
  "spratnost": 2,
  "posedujeDvoriste": true
}
### Testira menjanje podataka o kuci sa prosledjenim ID


PUT {{StanNaDanWebAPIService_HostAddress}}/Nekretnina/IzmeniStan/42
Content-Type:application/json

{
  "ulica": "Probna Ulica Izmenjena",
  "broj": "77",
  "kvadratura": 50,
  "brojTerasa": 1,
  "brojKupatila": 1,
  "brojSpavacihSoba": 1,
  "posedujeTV": true,
  "posedujeInternet": true,
  "posedujeKuhinju": true,
  "sprat": 2,
  "posedujeLift": true
}
### Testira promenu podataaka o stanu sa prosledjenim ID


DELETE {{StanNaDanWebAPIService_HostAddress}}/Nekretnina/ObrisiNekretninu/42
### Testira brisanje nekretnine sa prosledjenim ID


###---------------------------------DODATNA_OPREMA-------------------------------------------

GET {{StanNaDanWebAPIService_HostAddress}}/DodatnaOprema/VratiSvuDodatnuOpremuNekretnine/1
Accept:application/json
### Testira vracanje svih dodatnih oprema nekretnine sa prosledjenim ID


GET {{StanNaDanWebAPIService_HostAddress}}/DodatnaOprema/VratiDodatnuOpremu/1/1
Accept:application/json
### Testira vracanje dodatne opreme sa prosledjenim ID nekretnine i ID opreme iz te nekretnine


POST {{StanNaDanWebAPIService_HostAddress}}/DodatnaOprema/DodajDodatnuOpremu/1/4
Content-Type:application/json

{
  "tipOpreme": "TestOprema",
  "besplatnoKoriscenje": true,
  "cenaKoriscenja": 0

}
### Testira dodavanje nove dodatne opreme nekretnini sa prosledjenim ID


PUT {{StanNaDanWebAPIService_HostAddress}}/DodatnaOprema/IzmeniDodatnuOpremu/1/4
Content-Type:application/json

{
  "tipOpreme": "Izmenjeni test",
  "besplatnoKoriscenje": true,
  "cenaKoriscenja": 0
}
### Testira izmenu dodatne opreme sa prosledjenim ID nekretnine i ID opreme iz te nekretnine

DELETE {{StanNaDanWebAPIService_HostAddress}}/DodatnaOprema/ObrisiDodatnuOpremu/1/4
### Testira brisanje dodatne opreme (prethodno dodate kroz testove) iz nekretnine sa prosledjenim ID i prosledjenim ID opreme iz te nekretnine



###---------------------------------PARKING-----------------------------------------------------------

GET {{StanNaDanWebAPIService_HostAddress}}/Parking/VratiSveParkingeNekretnine/1
Accept:application/json
### Testira vracanje svih parking mesta iz baze podataka


GET {{StanNaDanWebAPIService_HostAddress}}/Parking/VratiParking/1/1
Accept:application/json
### Testira parkinga sa prosledjenim id na nivou nekretnine sa prosledjenim id


POST {{StanNaDanWebAPIService_HostAddress}}/Parking/DodajParking/1/2
Content-Type:application/json

{
  "besplatan": false,
  "cena": 1700,
  "uSastavuNekretnine": true,
  "uSastavuJavnogParkinga": false
}
### Testira dodavanje novog parkinga nekretnini sa prosledjenim id sa prosledjenim IDem parkinga


PUT {{StanNaDanWebAPIService_HostAddress}}/Parking/IzmeniParking/1/2
Content-Type:application/json

{
  "besplatan": false,
  "cena": 2000,
  "uSastavuNekretnine": true,
  "uSastavuJavnogParkinga": false
}
### Testira izmenu parkinga sa zadatim id iz nekretnine sa prosledjenim id


DELETE {{StanNaDanWebAPIService_HostAddress}}/Parking/ObrisiParking/1/2
### Testira brisanje prosledjenog parkinga


###--------------------------SAJTOVI_NEKRETNINE--------------------------------------------------------------


POST {{StanNaDanWebAPIService_HostAddress}}/SajtoviNekretnine/DodajSajtNekretnine/1/www.stanNaDan.com
### Testira dodavanje novog sajta nekretnini sa prosledjenim id


GET {{StanNaDanWebAPIService_HostAddress}}/SajtoviNekretnine/VratiSveSajtoveNekretnine/1
Accept:application/json
### Testira vracanje svih sajtova iz baze podataka za nekretninu sa prosledjenim id


GET {{StanNaDanWebAPIService_HostAddress}}/SajtoviNekretnine/VratiSajtNekretnine/www.stanNaDan.com/1
Accept:application/json
### Testira vracanje konkretnog sajta nekretnine sa prosledjenim id

PUT {{StanNaDanWebAPIService_HostAddress}}/SajtoviNekretnine/IzmeniSajtNekretnine/www.stanNaDan.com/www.novi.com/1
### Testiranje azuriranja sajta


DELETE {{StanNaDanWebAPIService_HostAddress}}/SajtoviNekretnine/ObrisiSajtNekretnine/www.stanNaDan.com/1
### Testira brisanje sajta


###------------------------------------BROJEVI_TELEFONA--------------------------------------------------------


POST {{StanNaDanWebAPIService_HostAddress}}/BrojeviTelefona/DodajBrojTelefona/1234567890123/+381%2069%205594999
### Testira dodavanje novog sajta nekretnini sa prosledjenim id


GET {{StanNaDanWebAPIService_HostAddress}}/BrojeviTelefona/VratiSveBrojeveTelefona/1234567890123
Accept:application/json
### Testira vracanje svih brojeva telefona iz baze podataka za fizicko lice sa prosledjenim jmbg


GET {{StanNaDanWebAPIService_HostAddress}}/BrojeviTelefona/VratiBrojTelefona/+381%2069%205594999/1234567890123
Accept:application/json
### Testira vracanje konkretnog telefona sa podacima fizickog lica sa prosledjenim jmbg

  
PUT {{StanNaDanWebAPIService_HostAddress}}/BrojeviTelefona/IzmeniBrojTelefona/+381%2069%205594999/+381%2069%204444999/1234567890123
### Testira izmenu starog telefona novim


DELETE {{StanNaDanWebAPIService_HostAddress}}/BrojeviTelefona/ObrisiBrojTelefona/+381%2069%204444999/1234567890123
### Testira brisanje broja telefona


###--------------------------------TELEFONI_KONTAKT_OSOBE--------------------------------------------------------------


POST {{StanNaDanWebAPIService_HostAddress}}/TelefoniKontaktOsobe/DodajTelefonKontaktOsobe/+381%2064%205594977/123456789
### Testira dodavanje novog sajta nekretnini sa prosledjenim id


GET {{StanNaDanWebAPIService_HostAddress}}/TelefoniKontaktOsobe/VratiSveTelefoneKontaktOsobe/123456789
Accept:application/json
### Testira vracanje svih brojeva telefona iz baze podataka za pravno lice sa prosledjenim pib


GET {{StanNaDanWebAPIService_HostAddress}}/TelefoniKontaktOsobe/VratiTelefonKontaktOsobe/+381%2064%205594977/123456789
Accept:application/json
### Testira vracanje konkretnog telefona sa podacima pravnog lica sa prosledjenim pib

  
PUT {{StanNaDanWebAPIService_HostAddress}}/TelefoniKontaktOsobe/IzmeniTelefonKontaktOsobe/+381%2064%205594977/+381%2064%205594399/123456789
### Testira izmenu pravnog lica sa zadatim brojevima i pib


DELETE {{StanNaDanWebAPIService_HostAddress}}/TelefoniKontaktOsobe/ObrisiTelefonKontaktOsobe/+381%2064%205594399/123456789
### Testira brisanje broja telefona


###------------------------------------------------SOBA---------------------------------------------------------------------------------------



POST {{StanNaDanWebAPIService_HostAddress}}/Soba/DodajSobu/4/3
### Testira dodavanje nove sobe nekretnini sa prosledjenim id


GET {{StanNaDanWebAPIService_HostAddress}}/Soba/VratiSveSobe
Accept:application/json
### Testira vracanje svih soba iz baze podataka za nekretninom sa prosledjenim id


GET {{StanNaDanWebAPIService_HostAddress}}/Soba/VratiSveSobeNekretnine/3
Accept:application/json
### Testira vracanje soba konkretne nekretnine

  
GET {{StanNaDanWebAPIService_HostAddress}}/Soba/VratiSobu/4/3
### Testira vracanje konkretne sobe konkretne nekretnine


DELETE {{StanNaDanWebAPIService_HostAddress}}/Soba/ObrisiSobu/4/3
### Testira brisanje sobe


###-------------------------------------ZAJEDNICKE_PROSTORIJE-------------------------------------------



POST {{StanNaDanWebAPIService_HostAddress}}/ZajednickeProstorije/DodajZajednickuProstoriju/1/3/Kuhinja
### Testira dodavanje nove zajednicke prostorije


GET {{StanNaDanWebAPIService_HostAddress}}/ZajednickeProstorije/VratiSveZajednickeProstorijeSobe/1/3
Accept:application/json
### Testira vracanje svih zajednickih prostorija sobe


GET {{StanNaDanWebAPIService_HostAddress}}/ZajednickeProstorije/VratiSveZajednickeProstorijeNajma/1
Accept:application/json
### Testira vracanje zajednickih prostorija najma


GET {{StanNaDanWebAPIService_HostAddress}}/ZajednickeProstorije/VratiZajednickuProstoriju/1/3/Kuhinja
Accept:application/json
### Testira vracanje konkretne zajednicke prostorije


PUT {{StanNaDanWebAPIService_HostAddress}}/ZajednickeProstorije/IzmeniZajednickuProstoriju/Kuhinja/Hodnik/1/3
### Testira izmenu zajednicke prostorije


DELETE {{StanNaDanWebAPIService_HostAddress}}/ZajednickeProstorije/ObrisiZajednickuProstoriju/1/3/Hodnik
### Testira brisanje zajednicke prostorije



###--------------------------------------NAJAM----------------------------------------------------------------------------


POST {{StanNaDanWebAPIService_HostAddress}}/Najam/DodajNajam/1205003587452/3
Content-Type:application/json

{
  "datumPocetka": "2024-05-30T05:03:38",
  "datumZavrsetka": "2024-05-30T05:03:38",
  "brojDana": 0,
  "cenaPoDanu": 1111,
  "popust": 11,
  "cenaSaPopustom": 987.555555555556,
  "zaradaOdDodatnihUsluga": 1000,
  "ukupnaCena": 1000,
  "provizijaAgencije": 11,
  "adresaNekretnine": "NIS, Ulica Svetozara Markovića 7"
}
### Testira dodavanje novog najma bez spoljnog saradnika



POST {{StanNaDanWebAPIService_HostAddress}}/Najam/DodajNajam/4444444444444/3?idSpoljnogSaradnika=1
Content-Type:application/json

{
  "datumPocetka": "2024-05-30T05:03:38",
  "datumZavrsetka": "2024-05-30T05:03:38",
  "brojDana": 0,
  "cenaPoDanu": 1111,
  "popust": 11,
  "cenaSaPopustom": 987.555555555556,
  "zaradaOdDodatnihUsluga": 1000,
  "ukupnaCena": 1000,
  "provizijaAgencije": 11,
  "adresaNekretnine": "NIS, Ulica Svetozara Markovića 7"
}
### Testira dodavanje novog najma sa spoljnim saradnikom


GET {{StanNaDanWebAPIService_HostAddress}}/Najam/VratiSveNajmove/1/3
Accept:application/json
### Testira vracanje svih brojeva telefona iz baze podataka za pravno lice sa prosledjenim pib


GET {{StanNaDanWebAPIService_HostAddress}}/Najam/VratiSveNajmoveNekretnine/3
Accept:application/json
### Testira vracanje konkretnog telefona sa podacima pravnog lica sa prosledjenim pib


GET {{StanNaDanWebAPIService_HostAddress}}/Najam/VratiNajam/84
Accept:application/json
### Testira vracanje konkretnog telefona sa podacima pravnog lica sa prosledjenim pib


PUT {{StanNaDanWebAPIService_HostAddress}}/Najam/IzmeniNajam/84
Content-Type:application/json

{
  "datumPocetka": "2024-03-30T05:07:38",
  "datumZavrsetka": "2024-05-30T05:03:38",
  "cenaPoDanu": 1000,
  "popust": 11,
  "cenaSaPopustom": 987.555555555556,
  "zaradaOdDodatnihUsluga": 1000,
  "ukupnaCena": 1000,
  "provizijaAgencije": 11
}
### Testira izmenu datuma pocetka i cene po danu


DELETE {{StanNaDanWebAPIService_HostAddress}}/Najam/ObrisiNajam/83
### Testira brisanje najma



###-----------------------------------IZNAJMLJENA_SOBA---------------------------------------------------------